/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import entity.GameData;
import entity.UserData;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import server.ServerServiceStub;
import server.game.ServerGameStub;
import utils.CryptMD5;
import utils.Pair;

/**
 *
 * @author Edoardo
 */
public class ControlFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControlFrame
     */
    CardLayout card;
    ClientServiceImpl clientService;
    ServerServiceStub serviceStub;
    UserData loggedUser;
    List<GameData> gameList;
    ClientGameImpl clientGame;
    boolean pswMod = false;
    boolean logged = false;
    DefaultTableModel gameTableModel;

    public ControlFrame() {
        gameTableModel = this.createGameTableModel();
        initComponents();
        initCustom();
        loggedUser = new UserData();
        try {
            Registry registry = LocateRegistry.getRegistry(1099);
            serviceStub = (ServerServiceStub) registry.lookup("Il Paroliere");
        } catch (NotBoundException | RemoteException e) {
            showMessageDialog(null, "Si è verificato un errore nella connessione... " + e.getLocalizedMessage());
        }

        clientService = ClientServiceImpl.ClientServiceImpl(this);

        card = (CardLayout) jPanel_main.getLayout();
        this.combo_Nplayers.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (combo_Nplayers.getSelectedIndex() != 5) {
                    btn_createGame_home.setEnabled(true);
                } else {
                    btn_createGame_home.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_sidebar = new javax.swing.JPanel();
        btn_profile = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_stats = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_main = new javax.swing.JPanel();
        jPanel_login = new javax.swing.JPanel();
        text_email_login = new javax.swing.JTextField();
        text_password_login = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        label_pswRecover = new javax.swing.JLabel();
        label_signin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_verify = new javax.swing.JLabel();
        jPanel_home = new javax.swing.JPanel();
        label_home_activeGames = new javax.swing.JLabel();
        label_home_createGame = new javax.swing.JLabel();
        btn_createGame_home = new javax.swing.JButton();
        text_gameName_home = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btn_partecipate_home = new javax.swing.JButton();
        combo_Nplayers = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableGameList = new javax.swing.JTable();
        jPanel_stats = new javax.swing.JPanel();
        combo_stats = new javax.swing.JComboBox<>();
        btn_search_stats = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel_profile = new javax.swing.JPanel();
        label_profile = new javax.swing.JLabel();
        text_name_profile = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        text_surname_profile = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        text_username_profile = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        text_email_profile = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        text_password_profile = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        text_repeatPassword_profile = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        btn_save_profile = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(79, 36, 107));
        setResizable(false);

        jPanel_sidebar.setBackground(new java.awt.Color(79, 36, 107));

        btn_profile.setBackground(new java.awt.Color(79, 36, 107));
        btn_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/icons8-user-32.png"))); // NOI18N
        btn_profile.setText("PROFILO");
        btn_profile.setBorder(null);
        btn_profile.setEnabled(false);
        btn_profile.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(79, 36, 107));
        btn_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/homeWhite32px.png"))); // NOI18N
        btn_home.setText("  HOME");
        btn_home.setBorder(null);
        btn_home.setEnabled(false);
        btn_home.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_stats.setBackground(new java.awt.Color(79, 36, 107));
        btn_stats.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_stats.setForeground(new java.awt.Color(255, 255, 255));
        btn_stats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/stats32px.png"))); // NOI18N
        btn_stats.setText("  STATS");
        btn_stats.setBorder(null);
        btn_stats.setEnabled(false);
        btn_stats.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statsActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(79, 36, 107));
        btn_logout.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(232, 17, 35));
        btn_logout.setText("LOGOUT");
        btn_logout.setBorder(null);
        btn_logout.setEnabled(false);
        btn_logout.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sidebarLayout = new javax.swing.GroupLayout(jPanel_sidebar);
        jPanel_sidebar.setLayout(jPanel_sidebarLayout);
        jPanel_sidebarLayout.setHorizontalGroup(
            jPanel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sidebarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_stats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(btn_profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_sidebarLayout.setVerticalGroup(
            jPanel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidebarLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        jPanel_title.setBackground(new java.awt.Color(137, 109, 156));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Il Paroliere");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_main.setLayout(new java.awt.CardLayout());

        jPanel_login.setBackground(new java.awt.Color(255, 255, 255));

        text_email_login.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_email_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_login.setText("user@mail.com");
        text_email_login.setBorder(null);
        text_email_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_email_loginMouseClicked(evt);
            }
        });

        text_password_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_password_login.setText("jPasswordField1");
        text_password_login.setBorder(null);
        text_password_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_password_loginMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        btn_login.setBackground(new java.awt.Color(79, 36, 107));
        btn_login.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        label_pswRecover.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label_pswRecover.setForeground(new java.awt.Color(255, 0, 51));
        label_pswRecover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_pswRecover.setText("Recupera password");
        label_pswRecover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_pswRecoverMouseClicked(evt);
            }
        });

        label_signin.setBackground(new java.awt.Color(255, 255, 255));
        label_signin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label_signin.setForeground(new java.awt.Color(79, 36, 107));
        label_signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signin.setText("Non hai un account? Registrati!");
        label_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_signinMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/user_90px.png"))); // NOI18N

        label_verify.setBackground(new java.awt.Color(255, 255, 255));
        label_verify.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label_verify.setForeground(new java.awt.Color(79, 36, 107));
        label_verify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_verify.setText("Oppure, verifica il tuo account");
        label_verify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_verifyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(444, 444, 444))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1)
                                .addComponent(text_password_login, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_email_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)))
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_pswRecover, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_verify, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(365, 365, 365))))
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(text_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(text_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(label_pswRecover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_signin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_verify)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jPanel_main.add(jPanel_login, "login");

        jPanel_home.setBackground(new java.awt.Color(255, 255, 255));

        label_home_activeGames.setBackground(new java.awt.Color(137, 109, 156));
        label_home_activeGames.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        label_home_activeGames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home_activeGames.setText("Partite Attive:");

        label_home_createGame.setBackground(new java.awt.Color(137, 109, 156));
        label_home_createGame.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        label_home_createGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home_createGame.setText("Crea Partita:");

        btn_createGame_home.setBackground(new java.awt.Color(79, 36, 107));
        btn_createGame_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_createGame_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_createGame_home.setText("CREA");
        btn_createGame_home.setBorder(null);
        btn_createGame_home.setEnabled(false);
        btn_createGame_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createGame_homeActionPerformed(evt);
            }
        });

        text_gameName_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_gameName_home.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_gameName_home.setText("Nome Partita");
        text_gameName_home.setBorder(null);
        text_gameName_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_gameName_homeMouseClicked(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        btn_partecipate_home.setBackground(new java.awt.Color(79, 36, 107));
        btn_partecipate_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_partecipate_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_partecipate_home.setText("PARTECIPA");
        btn_partecipate_home.setBorder(null);
        btn_partecipate_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partecipate_homeActionPerformed(evt);
            }
        });

        combo_Nplayers.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        combo_Nplayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "Numero Giocatori?" }));
        combo_Nplayers.setSelectedIndex(5);
        combo_Nplayers.setToolTipText("");
        combo_Nplayers.setBorder(null);
        combo_Nplayers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_NplayersItemStateChanged(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        jTableGameList.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTableGameList.setModel(gameTableModel);
        jTableGameList.setGridColor(new java.awt.Color(255, 255, 255));
        jTableGameList.setSelectionBackground(new java.awt.Color(23, 113, 230));
        jTableGameList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableGameList.setShowHorizontalLines(false);
        jTableGameList.setShowVerticalLines(false);
        jTableGameList.getTableHeader().setResizingAllowed(false);
        jTableGameList.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableGameList);

        javax.swing.GroupLayout jPanel_homeLayout = new javax.swing.GroupLayout(jPanel_home);
        jPanel_home.setLayout(jPanel_homeLayout);
        jPanel_homeLayout.setHorizontalGroup(
            jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_home_activeGames, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(label_home_createGame, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(139, 139, 139)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_homeLayout.createSequentialGroup()
                        .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_gameName_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_homeLayout.createSequentialGroup()
                        .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combo_Nplayers, 0, 254, Short.MAX_VALUE)
                            .addComponent(btn_createGame_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100))))
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btn_partecipate_home, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_homeLayout.setVerticalGroup(
            jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_home_createGame, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_home_activeGames, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_homeLayout.createSequentialGroup()
                        .addComponent(text_gameName_home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_Nplayers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btn_createGame_home, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(btn_partecipate_home, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel_main.add(jPanel_home, "home");

        jPanel_stats.setBackground(new java.awt.Color(255, 255, 255));

        combo_stats.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        combo_stats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_stats.setBorder(null);

        btn_search_stats.setBackground(new java.awt.Color(79, 36, 107));
        btn_search_stats.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_search_stats.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_stats.setText("CERCA");
        btn_search_stats.setBorder(null);
        btn_search_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_statsActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/combo_chart_96px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_statsLayout = new javax.swing.GroupLayout(jPanel_stats);
        jPanel_stats.setLayout(jPanel_statsLayout);
        jPanel_statsLayout.setHorizontalGroup(
            jPanel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_statsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_statsLayout.createSequentialGroup()
                        .addComponent(combo_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btn_search_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_statsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(452, 452, 452))))
        );
        jPanel_statsLayout.setVerticalGroup(
            jPanel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_statsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_stats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(473, 473, 473))
        );

        jPanel_main.add(jPanel_stats, "stats");

        jPanel_profile.setBackground(new java.awt.Color(255, 255, 255));

        label_profile.setBackground(new java.awt.Color(137, 109, 156));
        label_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        label_profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/male_user_90px.png"))); // NOI18N

        text_name_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_name_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_name_profile.setText("Nome");
        text_name_profile.setBorder(null);
        text_name_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_name_profileMouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        text_surname_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_surname_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_surname_profile.setText("Cognome");
        text_surname_profile.setBorder(null);
        text_surname_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_surname_profileMouseClicked(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        text_username_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_username_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_username_profile.setText("Username");
        text_username_profile.setBorder(null);
        text_username_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_username_profileMouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        text_email_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_email_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_profile.setText("Email");
        text_email_profile.setBorder(null);
        text_email_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_email_profileMouseClicked(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        text_password_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_password_profile.setText("password");
        text_password_profile.setBorder(null);
        text_password_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_password_profileMouseClicked(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        text_repeatPassword_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_repeatPassword_profile.setText("password");
        text_repeatPassword_profile.setBorder(null);
        text_repeatPassword_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_repeatPassword_profileMouseClicked(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        btn_save_profile.setBackground(new java.awt.Color(79, 36, 107));
        btn_save_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_save_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_profile.setText("SALVA ");
        btn_save_profile.setBorder(null);
        btn_save_profile.setEnabled(false);
        btn_save_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_profileLayout = new javax.swing.GroupLayout(jPanel_profile);
        jPanel_profile.setLayout(jPanel_profileLayout);
        jPanel_profileLayout.setHorizontalGroup(
            jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_profileLayout.createSequentialGroup()
                .addGroup(jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_profileLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addGroup(jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_repeatPassword_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_password_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_email_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_username_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_surname_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_name_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 315, Short.MAX_VALUE))
                    .addComponent(label_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_profileLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(btn_save_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_profileLayout.setVerticalGroup(
            jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_profileLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(label_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_name_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(text_surname_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(text_username_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_email_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_password_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_repeatPassword_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel_main.add(jPanel_profile, "profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCustom() {
        //TABLE settings
        DefaultTableCellRenderer headerBgRender = new DefaultTableCellRenderer();
        headerBgRender.setBackground(Color.decode("#FFFFFF"));
        headerBgRender.setForeground(Color.decode("#FFFFFF"));
        DefaultTableCellRenderer rightAlignmentRender = new DefaultTableCellRenderer();
        rightAlignmentRender.setHorizontalAlignment(JLabel.RIGHT);

        this.jTableGameList.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(headerBgRender);
        this.jTableGameList.getTableHeader().getColumnModel().getColumn(1).setHeaderRenderer(headerBgRender);
        this.jTableGameList.getColumnModel().getColumn(1).setCellRenderer(rightAlignmentRender);
        this.jTableGameList.getColumnModel().getColumn(0).setPreferredWidth(350);
        this.jTableGameList.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.jScrollPane3.getViewport().setBackground(Color.white);
    }

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String email = this.text_email_login.getText();
        String password = String.valueOf(this.text_password_login.getPassword());
        //CHECK fields
        if (email.equals("") || password.equals("")) {
            showMessageDialog(null, "Compilare i campi richiesti");
            return;
        }
        //CHECK email
        if (GuiUtility.isEmailCorrect(email) == false) {
            showMessageDialog(null, "Formato Email errato");
            return;
        }
        //CALL login method
        logged = false;

        try {
            Pair<Integer, UserData> res = serviceStub.login(email, CryptMD5.crypt(password));

            if (res.getLast() != null) {
                loggedUser = res.getLast();
                logged = true;
                serviceStub.addObserver(res.getLast().getNickname(), clientService);
            } else {
                switch (res.getFirst()) {
                    case 0:
                        showMessageDialog(null, "Email errata!");
                        break;
                    case 1:
                        showMessageDialog(null, "Password errata!");
                        break;
                    case 2:
                        VerifyUser verify = new VerifyUser(this, true);
                        verify.setVisible(true);
                        break;
                }

            }
        } catch (RemoteException ex) {
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (logged) {
            btn_home.setEnabled(true);
            btn_stats.setEnabled(true);
            btn_profile.setEnabled(true);
            btn_logout.setEnabled(true);
            card.show(jPanel_main, "home");
            this.fillGameTable();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void label_pswRecoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_pswRecoverMouseClicked
        // TODO add your handling code here:
        RecoverPsw recover = new RecoverPsw(this, true, serviceStub);
        recover.setVisible(true);
    }//GEN-LAST:event_label_pswRecoverMouseClicked

    private void label_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_signinMouseClicked
        // TODO add your handling code here:
        RegisterUser register = new RegisterUser(this, true, serviceStub);
        register.setVisible(true);
    }//GEN-LAST:event_label_signinMouseClicked

    private void text_email_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_loginMouseClicked
        // TODO add your handling code here:
        this.text_email_login.setText("");
    }//GEN-LAST:event_text_email_loginMouseClicked

    private void text_password_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_password_loginMouseClicked
        // TODO add your handling code here:
        this.text_password_login.setText("");
    }//GEN-LAST:event_text_password_loginMouseClicked

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        this.fillGameTable();
        card.show(jPanel_main, "home");
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statsActionPerformed
        // TODO add your handling code here:
        card.show(jPanel_main, "stats");
    }//GEN-LAST:event_btn_statsActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        // TODO add your handling code here:

        //fillUserProfileData(loggedUser);
        card.show(jPanel_main, "profile");
        showMessageDialog(null, loggedUser.getEmail());
        fillUserProfileData(loggedUser);
    }//GEN-LAST:event_btn_profileActionPerformed


    private void btn_createGame_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createGame_homeActionPerformed
        // TODO add your handling code here:
        if (GuiUtility.isEmpty(this.text_gameName_home)) {
            showMessageDialog(null, "Inserire un nome della partita");
            return;
        }
        ServerGameStub serverGameStub = null;
        try {
            //creare qua clientGame --> togliere il parametro e mettere un setter in lobby
            this.clientGame = new ClientGameImpl();
            Lobby lobby = new Lobby(this, true, loggedUser, clientGame);
            this.clientGame.setGuiLobby(lobby);
            serverGameStub = serviceStub.createGame(this.loggedUser.getNickname(), this.text_gameName_home.getText(), this.combo_Nplayers.getSelectedIndex() + 2, clientGame);
            lobby.setServerGameStub(serverGameStub);
            lobby.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_createGame_homeActionPerformed

    private void btn_partecipate_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partecipate_homeActionPerformed
        // TODO add your handling code here:
        ServerGameStub serverGameStub = null;
        int gameIndex = this.jTableGameList.getSelectedRow();

        try {
            this.clientGame = new ClientGameImpl();
            Lobby lobby = new Lobby(this, true, loggedUser, clientGame);
            this.clientGame.setGuiLobby(lobby);
            serverGameStub = serviceStub.partecipate(this.loggedUser.getNickname(), gameList.get(gameIndex).getId(), clientGame);
            lobby.setServerGameStub(serverGameStub);
            lobby.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_partecipate_homeActionPerformed

    private void text_gameName_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_gameName_homeMouseClicked
        // TODO add your handling code here:
        this.text_gameName_home.setText("");
    }//GEN-LAST:event_text_gameName_homeMouseClicked

    private void label_verifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_verifyMouseClicked
        // TODO add your handling code here:
        VerifyUser verify = new VerifyUser(this, true);
        verify.setVisible(true);
    }//GEN-LAST:event_label_verifyMouseClicked

    private void btn_search_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_statsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search_statsActionPerformed

    private void text_name_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_name_profileMouseClicked
        // TODO add your handling code here:
        this.btn_save_profile.setEnabled(true);
    }//GEN-LAST:event_text_name_profileMouseClicked

    private void text_surname_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_surname_profileMouseClicked
        // TODO add your handling code here:
        this.btn_save_profile.setEnabled(true);
    }//GEN-LAST:event_text_surname_profileMouseClicked

    private void text_username_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_username_profileMouseClicked
        // TODO add your handling code here:
        this.btn_save_profile.setEnabled(true);
    }//GEN-LAST:event_text_username_profileMouseClicked

    private void text_email_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_profileMouseClicked
        // TODO add your handling code here:
        this.btn_save_profile.setEnabled(true);
    }//GEN-LAST:event_text_email_profileMouseClicked

    private void text_password_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_password_profileMouseClicked
        // TODO add your handling code here:
        this.btn_save_profile.setEnabled(true);
        pswMod = true;
    }//GEN-LAST:event_text_password_profileMouseClicked

    private void text_repeatPassword_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_repeatPassword_profileMouseClicked
        // TODO add your handling code here:
        this.btn_save_profile.setEnabled(true);
        pswMod = true;
    }//GEN-LAST:event_text_repeatPassword_profileMouseClicked

    private void btn_save_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_profileActionPerformed
        // TODO add your handling code here:
        UserData updatedUser;
        //CHECK not empty
        if (GuiUtility.isEmpty(this.text_email_profile) || GuiUtility.isEmpty(this.text_name_profile) || GuiUtility.isEmpty(this.text_surname_profile) || GuiUtility.isEmpty(this.text_username_profile) || GuiUtility.isEmpty(this.text_password_profile) || GuiUtility.isEmpty(this.text_repeatPassword_profile)) {
            showMessageDialog(null, "Compilare tutti i campi");
            return;
        }
        //CHECK email
        if (GuiUtility.isEmailCorrect(this.text_email_profile.getText()) == false) {
            showMessageDialog(null, "Formato Email errato");
            return;
        }
        //CHECK psw = repeatPsw
        if (GuiUtility.isPasswordMatching(this.text_password_profile, this.text_password_profile) == false) {
            showMessageDialog(null, "Le password non coincidono");
            return;
        }
        //SET new profile data
        updatedUser = new UserData();
        updatedUser.setEmail(this.text_email_profile.getText());
        updatedUser.setFirstName(this.text_name_profile.getText());
        updatedUser.setLastName(this.text_surname_profile.getText());
        updatedUser.setNickname(this.text_username_profile.getText());

        updatedUser.setActivationCode("12345678");
        if (pswMod) {
            updatedUser.setPassword(CryptMD5.crypt(String.valueOf(this.text_password_profile.getPassword())));
            pswMod = false;
        } else {
            updatedUser.setPassword(loggedUser.getPassword());
        }

        try {
            //CALL update method and update loggedUser with updatedUser
            loggedUser = serviceStub.updateUserData(updatedUser, loggedUser.getNickname());
        } catch (RemoteException ex) {
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        //DISABLE save button
        this.btn_save_profile.setEnabled(false);
    }//GEN-LAST:event_btn_save_profileActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        try {
            //CALL logout method
            serviceStub.logout(this.loggedUser.getNickname());
            loggedUser = null;
            //fare graficamente logout
            card.show(jPanel_main, "login");
            logged = false;
            btn_home.setEnabled(false);
            btn_stats.setEnabled(false);
            btn_profile.setEnabled(false);
            btn_logout.setEnabled(false);

        } catch (RemoteException ex) {
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void combo_NplayersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_NplayersItemStateChanged
        // TODO add your handling code here:
        if (this.combo_Nplayers.getSelectedIndex() != 5) {
            this.btn_createGame_home.setEnabled(true);
        }
    }//GEN-LAST:event_combo_NplayersItemStateChanged

    private void fillUserProfileData(UserData user) {
        text_email_profile.setText(user.getEmail());
        text_name_profile.setText(user.getFirstName());
        text_surname_profile.setText(user.getLastName());
        text_username_profile.setText(user.getNickname());
        text_password_profile.setText(user.getPassword());
        text_repeatPassword_profile.setText(user.getPassword());
    }

    //UTILITY
    private DefaultTableModel createGameTableModel() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("");
        model.addColumn("");
        //model.setRowCount(0);
        return model;
    }

    private void clearTable(DefaultTableModel model) {
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); ++i) {
                model.removeRow(i);
            }
        }
    }

    public void fillGameTable() {
        //this.clearTable((DefaultTableModel) this.jTableGameList.getModel());
        // this.jTableGameList.removeAll();
        //this.jTableGameList.updateUI();
        
        this.clearTable(gameTableModel);
        
        showMessageDialog(null, "code update check 6");

        //GET fresh game list
        System.out.println("Prima");
        gameList = clientService.getGamesList(); //controllare che nn sia nullo!
        System.out.println("filltable "+clientService.getGamesList().size());
        //gameList = new ArrayList<GameData>();

        //TEST ADDING VALUES
        /*GameData test = new GameData("PartitaEdoardoBianchi", 3);
        test.setId(1);
        test.addPlayer("marco");
        test.addPlayer("giovanni");
        gameList.add(test);
        GameData test1 = new GameData("PartitaSandro", 6);
        test1.setId(2);
        test1.addPlayer("sandro");
        test1.addPlayer("rocco");
        gameList.add(test1);
        GameData test2 = new GameData("PartitaMia", 5);
        test2.setId(3);
        test2.addPlayer("gigi");
        test2.addPlayer("rocco");
        gameList.add(test2);
        //END
*/
        //ADD to table
        Object rowData[] = new Object[2];
        for (GameData tmp : gameList) {
            if (tmp != null) {
                rowData[0] = tmp.getId() + " " + tmp.getName() + " " + "Creatore";
                rowData[1] = tmp.getPlayersList().size() + "/" + tmp.getNumPlayers();
                gameTableModel.addRow(rowData);
            }
        }

        //this.jTableGameList.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        System.setProperty("java.security.policy", "file:./resources/policy.policy");
        if (System.getSecurityManager() == null) {
            System.setSecurityManager(new SecurityManager());
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createGame_home;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_partecipate_home;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_save_profile;
    private javax.swing.JButton btn_search_stats;
    private javax.swing.JButton btn_stats;
    private javax.swing.JComboBox<String> combo_Nplayers;
    private javax.swing.JComboBox<String> combo_stats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_home;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_profile;
    private javax.swing.JPanel jPanel_sidebar;
    private javax.swing.JPanel jPanel_stats;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableGameList;
    private javax.swing.JLabel label_home_activeGames;
    private javax.swing.JLabel label_home_createGame;
    private javax.swing.JLabel label_profile;
    private javax.swing.JLabel label_pswRecover;
    private javax.swing.JLabel label_signin;
    private javax.swing.JLabel label_verify;
    private javax.swing.JTextField text_email_login;
    private javax.swing.JTextField text_email_profile;
    private javax.swing.JTextField text_gameName_home;
    private javax.swing.JTextField text_name_profile;
    private javax.swing.JPasswordField text_password_login;
    private javax.swing.JPasswordField text_password_profile;
    private javax.swing.JPasswordField text_repeatPassword_profile;
    private javax.swing.JTextField text_surname_profile;
    private javax.swing.JTextField text_username_profile;
    // End of variables declaration//GEN-END:variables

}
