/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.CardLayout;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Edoardo
 */
public class ControlFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControlFrame
     */
    CardLayout card;
    
    public ControlFrame() {
        initComponents();
        //Fill with user data for the profile tab
        text_email_profile.setText("giorgio@gmail.com");
        text_name_profile.setText("giorgio");
        text_surname_profile.setText("minchia");
        text_username_profile.setText("giominchia98");
        text_password_profile.setText("password");
        text_repeatPassword_profile.setText("password");
        
        card = (CardLayout) jPanel_main.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_sidebar = new javax.swing.JPanel();
        btn_profile = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_stats = new javax.swing.JButton();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_main = new javax.swing.JPanel();
        jPanel_login = new javax.swing.JPanel();
        text_email_login = new javax.swing.JTextField();
        text_password_login = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        label_pswRecover = new javax.swing.JLabel();
        label_signin = new javax.swing.JLabel();
        jPanel_home = new javax.swing.JPanel();
        label_home_activeGames = new javax.swing.JLabel();
        label_home_createGame = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_createGame_home = new javax.swing.JButton();
        text_gameName_home = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btn_partecipate_home1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel_stats = new javax.swing.JPanel();
        jPanel_profile = new javax.swing.JPanel();
        label_profile = new javax.swing.JLabel();
        text_name_profile = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        text_surname_profile = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        text_username_profile = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        text_email_profile = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        text_password_profile = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        text_repeatPassword_profile = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        btn_save_profile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(79, 36, 107));
        setResizable(false);

        jPanel_sidebar.setBackground(new java.awt.Color(79, 36, 107));

        btn_profile.setBackground(new java.awt.Color(79, 36, 107));
        btn_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/icons8-user-32.png"))); // NOI18N
        btn_profile.setText("PROFILO");
        btn_profile.setBorder(null);
        btn_profile.setEnabled(false);
        btn_profile.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(79, 36, 107));
        btn_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/homeWhite32px.png"))); // NOI18N
        btn_home.setText("  HOME");
        btn_home.setBorder(null);
        btn_home.setEnabled(false);
        btn_home.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_stats.setBackground(new java.awt.Color(79, 36, 107));
        btn_stats.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_stats.setForeground(new java.awt.Color(255, 255, 255));
        btn_stats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/stats32px.png"))); // NOI18N
        btn_stats.setText("  STATS");
        btn_stats.setBorder(null);
        btn_stats.setEnabled(false);
        btn_stats.setPreferredSize(new java.awt.Dimension(589, 521));
        btn_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sidebarLayout = new javax.swing.GroupLayout(jPanel_sidebar);
        jPanel_sidebar.setLayout(jPanel_sidebarLayout);
        jPanel_sidebarLayout.setHorizontalGroup(
            jPanel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sidebarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_stats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(btn_profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_sidebarLayout.setVerticalGroup(
            jPanel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidebarLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_title.setBackground(new java.awt.Color(137, 109, 156));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Il Paroliere");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_main.setLayout(new java.awt.CardLayout());

        jPanel_login.setBackground(new java.awt.Color(255, 255, 255));

        text_email_login.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_email_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_login.setText("user@mail.com");
        text_email_login.setBorder(null);
        text_email_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_email_loginMouseClicked(evt);
            }
        });

        text_password_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_password_login.setText("jPasswordField1");
        text_password_login.setBorder(null);
        text_password_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_password_loginMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        btn_login.setBackground(new java.awt.Color(79, 36, 107));
        btn_login.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        label_pswRecover.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label_pswRecover.setForeground(new java.awt.Color(255, 0, 51));
        label_pswRecover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_pswRecover.setText("Recupera password");
        label_pswRecover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_pswRecoverMouseClicked(evt);
            }
        });

        label_signin.setBackground(new java.awt.Color(255, 255, 255));
        label_signin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label_signin.setForeground(new java.awt.Color(79, 36, 107));
        label_signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signin.setText("Non hai un account? Registrati!");
        label_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_signinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(444, 444, 444))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1)
                                .addComponent(text_password_login, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_email_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)))
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_pswRecover, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(365, 365, 365))))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(text_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(text_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(label_pswRecover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_signin)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jPanel_main.add(jPanel_login, "login");

        jPanel_home.setBackground(new java.awt.Color(255, 255, 255));

        label_home_activeGames.setBackground(new java.awt.Color(137, 109, 156));
        label_home_activeGames.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        label_home_activeGames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home_activeGames.setText("Partite Attive:");

        label_home_createGame.setBackground(new java.awt.Color(137, 109, 156));
        label_home_createGame.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        label_home_createGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home_createGame.setText("Crea Partita:");

        jList1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        btn_createGame_home.setBackground(new java.awt.Color(79, 36, 107));
        btn_createGame_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_createGame_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_createGame_home.setText("CREA");
        btn_createGame_home.setBorder(null);
        btn_createGame_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createGame_homeActionPerformed(evt);
            }
        });

        text_gameName_home.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_gameName_home.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_gameName_home.setText("Nome Partita");
        text_gameName_home.setBorder(null);
        text_gameName_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_gameName_homeMouseClicked(evt);
            }
        });
        text_gameName_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_gameName_homeActionPerformed(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        btn_partecipate_home1.setBackground(new java.awt.Color(79, 36, 107));
        btn_partecipate_home1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_partecipate_home1.setForeground(new java.awt.Color(255, 255, 255));
        btn_partecipate_home1.setText("PARTECIPA");
        btn_partecipate_home1.setBorder(null);
        btn_partecipate_home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partecipate_home1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "Numero Giocatori" }));
        jComboBox1.setSelectedIndex(5);
        jComboBox1.setToolTipText("");
        jComboBox1.setBorder(null);

        javax.swing.GroupLayout jPanel_homeLayout = new javax.swing.GroupLayout(jPanel_home);
        jPanel_home.setLayout(jPanel_homeLayout);
        jPanel_homeLayout.setHorizontalGroup(
            jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_home_activeGames, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(label_home_createGame, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_homeLayout.createSequentialGroup()
                        .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_gameName_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_homeLayout.createSequentialGroup()
                        .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, 254, Short.MAX_VALUE)
                            .addComponent(btn_createGame_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100))))
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btn_partecipate_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_homeLayout.setVerticalGroup(
            jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_home_createGame, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_home_activeGames, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_homeLayout.createSequentialGroup()
                        .addComponent(text_gameName_home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btn_createGame_home, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(btn_partecipate_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel_main.add(jPanel_home, "home");

        javax.swing.GroupLayout jPanel_statsLayout = new javax.swing.GroupLayout(jPanel_stats);
        jPanel_stats.setLayout(jPanel_statsLayout);
        jPanel_statsLayout.setHorizontalGroup(
            jPanel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jPanel_statsLayout.setVerticalGroup(
            jPanel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        jPanel_main.add(jPanel_stats, "stats");

        jPanel_profile.setBackground(new java.awt.Color(255, 255, 255));

        label_profile.setBackground(new java.awt.Color(137, 109, 156));
        label_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        label_profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_profile.setText("Profilo Utente");

        text_name_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_name_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_name_profile.setText("Nome");
        text_name_profile.setBorder(null);
        text_name_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_name_profileActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        text_surname_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_surname_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_surname_profile.setText("Cognome");
        text_surname_profile.setBorder(null);
        text_surname_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_surname_profileActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        text_username_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_username_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_username_profile.setText("Username");
        text_username_profile.setBorder(null);
        text_username_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_username_profileActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        text_email_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        text_email_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_profile.setText("Email");
        text_email_profile.setBorder(null);
        text_email_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_email_profileActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        text_password_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_password_profile.setText("jPasswordField1");
        text_password_profile.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        text_repeatPassword_profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_repeatPassword_profile.setText("jPasswordField1");
        text_repeatPassword_profile.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        btn_save_profile.setBackground(new java.awt.Color(79, 36, 107));
        btn_save_profile.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_save_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_profile.setText("SALVA ");
        btn_save_profile.setBorder(null);

        javax.swing.GroupLayout jPanel_profileLayout = new javax.swing.GroupLayout(jPanel_profile);
        jPanel_profile.setLayout(jPanel_profileLayout);
        jPanel_profileLayout.setHorizontalGroup(
            jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_profileLayout.createSequentialGroup()
                .addGroup(jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_profileLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addGroup(jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_repeatPassword_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_password_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_email_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_username_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_surname_profile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_name_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 315, Short.MAX_VALUE))
                    .addComponent(label_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_profileLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(btn_save_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_profileLayout.setVerticalGroup(
            jPanel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_profileLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(label_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_name_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(text_surname_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(text_username_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_email_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_password_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_repeatPassword_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel_main.add(jPanel_profile, "profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        boolean logged = true; //MUST BE FALSE!
        
        if (logged){
            btn_home.setEnabled(true);
            btn_stats.setEnabled(true);
            btn_profile.setEnabled(true);
            
            card.show(jPanel_main, "home");
        } else{
            //alert
            showMessageDialog(null, "Email / password errati");
        }
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void label_pswRecoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_pswRecoverMouseClicked
        // TODO add your handling code here:
        RecoverPsw recover = new RecoverPsw(this, true);
        recover.setVisible(true);
    }//GEN-LAST:event_label_pswRecoverMouseClicked

    private void label_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_signinMouseClicked
        // TODO add your handling code here:
        RegisterUser register = new RegisterUser(this, true);
        register.setVisible(true);
    }//GEN-LAST:event_label_signinMouseClicked

    private void text_email_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_loginMouseClicked
        // TODO add your handling code here:
        this.text_email_login.setText("");
    }//GEN-LAST:event_text_email_loginMouseClicked

    private void text_password_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_password_loginMouseClicked
        // TODO add your handling code here:
        this.text_password_login.setText("");
    }//GEN-LAST:event_text_password_loginMouseClicked

    private void text_name_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_name_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_name_profileActionPerformed

    private void text_surname_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_surname_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_surname_profileActionPerformed

    private void text_username_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_username_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_username_profileActionPerformed

    private void text_email_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_email_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_email_profileActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        card.show(jPanel_main, "home");
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statsActionPerformed
        // TODO add your handling code here:
        card.show(jPanel_main, "stats");
    }//GEN-LAST:event_btn_statsActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        // TODO add your handling code here:
        card.show(jPanel_main, "profile");
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_createGame_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createGame_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_createGame_homeActionPerformed

    private void text_gameName_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_gameName_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_gameName_homeActionPerformed

    private void btn_partecipate_home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partecipate_home1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_partecipate_home1ActionPerformed

    private void text_gameName_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_gameName_homeMouseClicked
        // TODO add your handling code here:
        this.text_gameName_home.setText("");
    }//GEN-LAST:event_text_gameName_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createGame_home;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_partecipate_home1;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_save_profile;
    private javax.swing.JButton btn_stats;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel_home;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_profile;
    private javax.swing.JPanel jPanel_sidebar;
    private javax.swing.JPanel jPanel_stats;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel label_home_activeGames;
    private javax.swing.JLabel label_home_createGame;
    private javax.swing.JLabel label_profile;
    private javax.swing.JLabel label_pswRecover;
    private javax.swing.JLabel label_signin;
    private javax.swing.JTextField text_email_login;
    private javax.swing.JTextField text_email_profile;
    private javax.swing.JTextField text_gameName_home;
    private javax.swing.JTextField text_name_profile;
    private javax.swing.JPasswordField text_password_login;
    private javax.swing.JPasswordField text_password_profile;
    private javax.swing.JPasswordField text_repeatPassword_profile;
    private javax.swing.JTextField text_surname_profile;
    private javax.swing.JTextField text_username_profile;
    // End of variables declaration//GEN-END:variables
}
