/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import entity.UserData;
import java.awt.Component;
import java.awt.Frame;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import server.game.ServerGameStub;

/**
 *
 * @author Edoardo
 */
public class Lobby extends javax.swing.JDialog {

    ServerGameStub gameStub;
    ClientGameImpl clientGame;
    UserData loggedUser;
    DefaultListModel lobbyListModel;
    String gameName = "";
    List<String> playerNames;

    /**
     * Creates new form Lobby
     */
    public Lobby(java.awt.Frame parent, boolean modal, UserData loggedUser, ClientGameImpl parClientGame) {
        super(parent, modal);
        lobbyListModel = new DefaultListModel<String>();
        playerNames = new ArrayList<>();
        initComponents();
        this.loggedUser = loggedUser;
        this.clientGame = parClientGame;

        this.fillPartecipant();
    }

    private Lobby(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setServerGameStub(ServerGameStub serverGameStub) {
        this.gameStub = serverGameStub;
    }

    public void setGameName(String parName) {
        this.gameName = parName;
    }

    public void openGameWindow() {
        GameWin guiGame = new GameWin(this, true, this.gameName, this.loggedUser);
        guiGame.setPlayerList(playerNames); //--> lobbylist
        guiGame.setClientGameStub(clientGame);
        guiGame.setServerGameStub(gameStub);
        this.clientGame.setGuiGame(guiGame);
        SwingUtilities.invokeLater(new Runnable() {
             public void run() {
                    guiGame.setVisible(true);
                               }
        });

        //this.setVisible(false);
        //this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_leave = new javax.swing.JButton();
        label_partecipantWait = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_lobby = new javax.swing.JList<>();
        jLabel_timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_leave.setBackground(new java.awt.Color(79, 36, 107));
        btn_leave.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_leave.setForeground(new java.awt.Color(255, 255, 255));
        btn_leave.setText("ESCI");
        btn_leave.setBorder(null);
        btn_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leaveActionPerformed(evt);
            }
        });

        label_partecipantWait.setBackground(new java.awt.Color(137, 109, 156));
        label_partecipantWait.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        label_partecipantWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_partecipantWait.setText("Attesa partecipanti");

        jList_lobby.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jList_lobby.setModel(lobbyListModel);
        jList_lobby.setEnabled(false);
        jScrollPane1.setViewportView(jList_lobby);

        jLabel_timer.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel_timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_timer.setText("30");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_partecipantWait, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_leave, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel_timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_partecipantWait, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_leave, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_timer)
                        .addGap(56, 56, 56))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leaveActionPerformed
        try {
            this.setVisible(false);
            this.dispose();
            this.gameStub.leaveGame(loggedUser.getNickname());
        } catch (RemoteException ex) {
            Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
        }
        //this.fillPartecipant();
        
    }//GEN-LAST:event_btn_leaveActionPerformed

    public void fillPartecipant() {
        playerNames = this.clientGame.getLobbyList();
        //this.jList_lobby.removeAll();
        //this.jList_lobby = new JList(playerNames.toArray());
        this.lobbyListModel.removeAllElements();
        this.lobbyListModel.addAll(playerNames);
    }

    public void updateTimer(int value) {
        this.jLabel_timer.setText(value + "");
    }

    public void disableLeaveBtn() {
        this.btn_leave.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lobby dialog = new Lobby(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_leave;
    private javax.swing.JLabel jLabel_timer;
    private javax.swing.JList<String> jList_lobby;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_partecipantWait;
    // End of variables declaration//GEN-END:variables
}
